name: "github-actions-dashboard"
description: "Generates dashboard containing Github Actions runs statistics"
inputs:
  repository:
    description: "Repository name with owner"
    required: true
    default: "${{ github.repository }}"
  cachedir:
    description: "Cache dir for fetched workflow runs, jobs and timings"
    required: false
    default: "./cache"
  token:
    description: "Auth token used for fetching data using Github API"
    required: false
    default: "${{ github.token }}"
  outputDir:
    description: "Output directory for generated report"
    required: false
    default: "./output"
runs:
  using: "node12"
  main: "dist/index.js"
