name: run itself

on:
  pull_request:
  push:

jobs:
  generate-dashboard:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate runs dashboard
        uses: wendigo/github-actions-dashboard@master
        with:
          repository: trinodb/trino
          token: "${{ secrets.accessToken }}"
